[package]
name = "keelson"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "2.25.2"
prost = "0.12"
prost-types = "0.12"

[build-dependencies]
prost-build = "0.12"
glob = "0.3"

[lib]
crate-type = ["lib"]
